spring.application.name=reserve-backend
server.port=8080

# ================================
# PostgreSQL / Neon
# ================================
spring.datasource.url=jdbc:postgresql://ep-lucky-base-az2sfe0y-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0PucYpZwXsx4
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / Hibernate
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ================================
# Cloudinary
# ================================
cloudinary.cloud-name=dsojdpkgh
cloudinary.api-key=228664891662689
cloudinary.api-secret=674DaaCmdpHSjx0P-F9YAGaXjv8

# ================================
# JWT
# ================================
jwt.secret=MySecret@9988
jwt.expiration-ms=86400000

# ================================
# CORS
# ================================
app.cors.allowed-origins=*

# ================================
# File Upload
# ================================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB